#!/bin/sh
# Automatic SSH jump host for IPv6-only hosts.
# Usage in ~/.ssh/config: ProxyCommand ~/.ssh/ipv6proxy %h %p
# If a host is reachable via IPv6, a direct connection is made.
# Otherwise a jump host is used (which shall support IPv6).

if ping6 -c1 $1 >/dev/null 2>&1; then
	exec nc -6 $1 $2
else
	exec ssh -q callisto "nc -6 $1 $2"
fi
