#!/bin/sh
# Automatic SSH jump host for IPv6-only hosts.
# Usage in ~/.ssh/config: ProxyCommand ~/.ssh/ipv6proxy <jumphost> %h %p
# If a host is reachable via IPv6, a direct connection is made.
# Otherwise a jump host is used (which shall support IPv6).

if ping6 -c1 $2 >/dev/null 2>&1; then
	exec nc -6 $2 $3
else
	exec ssh -q $1 "nc -6 $2 $3"
fi
