[alias]
ci-check = "check --workspace --all-targets --all-features"
ci-clippy = "clippy --workspace --all-targets --all-features" # -- --deny warnings --allow deprecated
ci-fmt = "fmt --workspace -- --check"
ci-test = "test --workspace --all-targets --all-features"

[net]
#git-fetch-with-cli = true
